### ISSUE TITLE
Add a Contributors section to the README

### ISSUE THREAD

**Issue by nizarmah** [MuleDerby/veles#1]
Acceptance criteria:
* Contributors section added to the README
* Show the username, avatar, and role similarly to https://github.com/reobin/typewritten
    * Figure out a way to retrieve the user id for all contributors by using "Inspect Element"

Try making the change to master and push directly to master. Once that doesn't work, figure out how to create a pull request and request my review there...

Also, a lot of the tasks will be unclear because you need to tackle them yourself, so they stick longer in your head.

**Comment by nizarmah** [comment]
@Vetzio adding the information manually, for now, should be enough.

**Comment by Vetzio** [comment]
Hey @nizarmah ! I'm still working through the HTML lessons in TOP, but I wanted to check back on this issue. 

I believe I can manually add a heading for the Contributors section (Still working on looking into pull requests), but the second bullet point for this issue has been more elusive to figure out. 

I came across an "all-contributions" bot, and I believe this may be what typewritten uses. Should I look into implementing the bot, or is there a way I can access contributor's username, avatar, and role manually? Is that related to the "inspect element" note?

**Comment by nizarmah** [comment]
Hey @Vetzio! Glad you're working on the lessons and this in parallel.

For this pull request, let's add everything manually for now, no bots.
Write the HTML yourself and add it to the README.md via a pull request.
It's usually a better practice to automate once a similar ticket/issue repeats 3 times or more.
Otherwise, it's not worth it to put in the extra effort. 

You already have our usernames and roles, considering you know what each of us contributes to this project. We can just link to the user's profile. The avatar will require "inspecting elements" (check Developer Tools in Chrome).
